import { createClient } from "../../supabase/client";

interface EmailGenerationParams {
  lead: {
    company_name: string;
    niche: string | null;
    location: string | null;
    company_context: string | null;
  };
  yourCompany: string;
  yourService: string;
  tone: 'Direct' | 'Aggressive' | 'Surgical';
  customPainPoint?: string;
  userId: string;
  senderName?: string;   // Real name from SMTP account e.g. "Alice Smith"
  senderEmail?: string;  // Real email from SMTP account e.g. "alice@gmail.com"
  senderTitle?: string;  // Optional title e.g. "Executive Sales"
}

// ── System message ────────────────────────────────────────────────────────────
function buildSystemMessage(senderName: string, senderTitle: string): string {
  return `You are a senior B2B sales executive writing cold outreach emails on behalf of Pryro.

EXACT FORMAT TO FOLLOW — mirror this structure precisely:

---
[One sentence — state something true and relevant about their industry or business situation. No compliments. No "I noticed". Just a plain observation.]

[One or two sentences — mention what Pryro does, but keep it brief and humble. Do NOT list features. Do NOT say "we help companies like yours". Say what it does in plain language, like you're explaining it to a friend.]

[One sentence — a soft ask. Request a short call to see if it makes sense. Frame it as "if it's relevant" or "only if it makes sense for you". Never pressure.]

Best regards,
${senderName}
${senderTitle}
Pryro
---

BODY RULES — this is the most important section:
- Maximum 80 words total. Count them. Cut anything over 80.
- Write like a human, not a company. Use "I" not "we" where possible.
- ONE idea per paragraph. Three short paragraphs maximum.
- Do NOT mention: "manual workflows", "Excel-based operations", "fragmented tools", "unified platform", "operational efficiency", "workflow management", "scale effectively", "save time", "reduce manual work"
- Do NOT use any of these phrases: "companies like yours", "help you achieve", "I believe", "I think you'll find", "this could be a game-changer", "cutting-edge", "revolutionary"
- No bullet points. No bold text. No markdown. Plain sentences only.
- The email should sound like it was written in 3 minutes by a real person, not generated by AI.

SUBJECT LINE RULES:

Write ONE unique subject line per email. It must feel like a real person typed it — direct, humble, slightly personal. 6 to 8 words. Make the recipient curious enough to open without knowing exactly what it is.

THE SUBJECT MUST FOLLOW THIS EXACT STYLE:
- Sounds like it came from a colleague or someone who knows their business
- Creates mild curiosity — they wonder "what is this about?"
- Never sounds like marketing, mass email, or a sales pitch
- References their company name OR their industry/niche — never both
- Humble tone — not pushy, not urgent, not salesy

REQUIRED: Pick ONE formula and fill it in for this specific recipient:

Formula A — Personal thought: "Had a thought about [Company Name]"
Formula B — Humble offer: "Something that might help [Company Name]"
Formula C — Soft curiosity: "Quick idea for your [niche] team"
Formula D — Human ask: "Worth a 10-minute chat, [Company Name]?"
Formula E — Peer insight: "What other [niche] owners are doing differently"
Formula F — Specific pain: "Cutting manual work for [niche] businesses"
Formula G — Direct value: "Helping [Company Name] save time on admin"

RULES:
- 6 to 8 words — count every word before finalizing
- Use the actual company name OR the niche — not both in the same subject
- NEVER use: "ERP", "partnership", "collaboration", "opportunity", "solution", "platform", "streamline", "leverage", "synergy"
- No exclamation marks, no ALL CAPS, no emojis
- Vary the formula — do not use the same formula twice in a row

BANNED WORDS AND PHRASES (never use any of these):
- "reach out", "I noticed", "I came across", "I hope this email finds you well",
  "I wanted to", "just checking in", "touching base", "circle back",
  "synergy", "leverage", "game-changer", "revolutionary", "cutting-edge",
  "excited to", "thrilled to", "I am writing to", "please don't hesitate",
  "feel free to", "at your earliest convenience", "as per", "going forward",
  "Unlock", "Exploring Synergies", "Streamline", "I'd love to",
  "I would love to", "would love to", "Quick question", "Quick Question",
  "manual workflows", "Excel-based operations", "fragmented tools",
  "unified platform", "operational efficiency", "workflow management",
  "scale effectively", "save time", "reduce manual work",
  "companies like yours", "help you achieve", "I believe you'll find"

SIGNATURE FORMAT — must be exactly this, no variations:
Best regards,
${senderName}
${senderTitle}
Pryro

NEVER write the signature as "Best regards, ${senderName} | Pryro" — it must be on separate lines.

TONE RULES:
- Humble but confident — like a professional colleague, not a salesperson
- Conversational and human — short sentences, plain language
- Never pushy, never desperate, never overly formal
- 100–160 words max for the body

ANTI-SPAM RULES:
- Plain text only. No markdown, no asterisks, no bold, no bullet points.
- Short paragraphs separated by blank lines.
- No spam words: free, guarantee, limited time, act now, click here, earn money, no risk, buy now, special offer, urgent, winner.
- No excessive punctuation (!!!, ???).
- One CTA only — a short meeting request.
- The signature MUST be on separate lines exactly as:
  Best regards,
  ${senderName}
  ${senderTitle}
  Pryro
- NEVER write "Best regards, Name | Pryro" on one line — always separate lines.

Respond ONLY in this exact format:
SUBJECT: [subject line — must be from the approved list above, 5-8 words]
BODY: [email body]`;
}

// ── Tone additions ────────────────────────────────────────────────────────────
const TONE_ADDITIONS: Record<string, string> = {
  Direct:   `Tone: Direct and concise. Open with the business context in one sentence. State the value proposition clearly. End with a simple meeting request. No filler words. Max 120 words.`,
  Aggressive: `Tone: Confident and opportunity-focused. Open with a specific industry challenge or missed opportunity. Make the value proposition impossible to ignore. CTA: ask for a 10-minute call this week. Max 140 words.`,
  Surgical: `Tone: Hyper-personalized and consultative. Reference their specific industry and business context. Sound like a trusted advisor identifying a gap, not a vendor pitching a product. Max 150 words.`,
};

// ── Strip markdown from AI output ────────────────────────────────────────────
function stripMarkdown(text: string): string {
  return text
    .replace(/\*\*(.+?)\*\*/g, "$1")
    .replace(/\*(.+?)\*/g, "$1")
    .replace(/^#{1,6}\s+/gm, "")
    .replace(/^[-*+]\s+/gm, "")
    .replace(/`(.+?)`/g, "$1")
    .replace(/_{1,2}(.+?)_{1,2}/g, "$1")
    .trim();
}

export async function generateAIEmail(params: EmailGenerationParams): Promise<{ subject: string; body: string }> {
  const { lead, yourCompany, yourService, tone, customPainPoint, userId,
          senderName: paramSenderName, senderEmail: paramSenderEmail, senderTitle: paramSenderTitle } = params;

  // Fetch active AI provider
  const providerRes = await fetch(`/api/ai-provider?userId=${userId}`);
  if (!providerRes.ok) {
    let msg = "No active AI provider configured. Please set up AI in Settings.";
    try {
      const err = await providerRes.json();
      msg = err.error || err.details || msg;
    } catch {}
    throw new Error(msg);
  }
  const aiProvider = await providerRes.json();

  // Fetch sender name from SMTP account if not provided
  let senderName = paramSenderName || '';
  let senderTitle = paramSenderTitle || 'Executive Sales';

  if (!senderName) {
    try {
      const supabase = (await import("../../supabase/client")).createClient();
      const { data: smtpAccounts } = await supabase
        .from('smtp_accounts')
        .select('email, sender_name')
        .eq('user_id', userId)
        .eq('status', 'active')
        .order('sent_today', { ascending: true })
        .limit(1);

      if (smtpAccounts && smtpAccounts.length > 0) {
        const account = smtpAccounts[0];
        // Use sender_name if set, otherwise derive from email
        senderName = account.sender_name ||
          account.email.split('@')[0]
            .replace(/[._\-]/g, ' ')
            .replace(/\b\w/g, (c: string) => c.toUpperCase());
      }
    } catch {
      // Fallback — use a generic name
    }
  }

  if (!senderName) senderName = 'Sales Team';

  const SYSTEM_MESSAGE = buildSystemMessage(senderName, senderTitle);

  // Build compact user prompt
  const companyContext = lead.company_context ? lead.company_context.slice(0, 300) : "";

  const userPrompt = `Write a Pryro outreach email.
Recipient: ${lead.company_name} | ${lead.niche || "Business"} | ${lead.location || ""}${companyContext ? `\nContext: ${companyContext}` : ""}${customPainPoint ? `\nPain point: ${customPainPoint}` : ""}
${TONE_ADDITIONS[tone]}`;

  // ── Call the active AI provider ───────────────────────────────────────────
  let aiResponse = "";

  if (aiProvider.provider === "openai") {
    const res = await fetch("https://api.openai.com/v1/chat/completions", {
      method: "POST",
      headers: { "Content-Type": "application/json", Authorization: `Bearer ${aiProvider.api_key}` },
      body: JSON.stringify({
        model: aiProvider.active_model || "gpt-4o-mini",
        messages: [{ role: "system", content: SYSTEM_MESSAGE }, { role: "user", content: userPrompt }],
        temperature: 0.4,
        max_tokens: 400,
      }),
    });
    if (!res.ok) throw new Error(`OpenAI API error: ${res.statusText}`);
    const data = await res.json();
    aiResponse = data.choices[0].message.content;

  } else if (aiProvider.provider === "anthropic") {
    const res = await fetch("https://api.anthropic.com/v1/messages", {
      method: "POST",
      headers: { "Content-Type": "application/json", "x-api-key": aiProvider.api_key, "anthropic-version": "2023-06-01" },
      body: JSON.stringify({
        model: aiProvider.active_model || "claude-3-5-haiku-20241022",
        max_tokens: 400,
        system: SYSTEM_MESSAGE,
        messages: [{ role: "user", content: userPrompt }],
      }),
    });
    if (!res.ok) throw new Error(`Anthropic API error: ${res.statusText}`);
    const data = await res.json();
    aiResponse = data.content[0].text;

  } else if (aiProvider.provider === "groq") {
    const res = await fetch("https://api.groq.com/openai/v1/chat/completions", {
      method: "POST",
      headers: { "Content-Type": "application/json", Authorization: `Bearer ${aiProvider.api_key}` },
      body: JSON.stringify({
        model: aiProvider.active_model || "llama-3.1-8b-instant",
        messages: [{ role: "system", content: SYSTEM_MESSAGE }, { role: "user", content: userPrompt }],
        temperature: 0.4,
        max_tokens: 400,
      }),
    });
    if (!res.ok) {
      let errText = ""; try { errText = await res.text(); } catch {}
      let errJson: any = null; try { errJson = JSON.parse(errText); } catch {}
      const msg = errJson?.error?.message || errText.slice(0, 200) || res.statusText;
      if (res.status === 401) throw new Error("Groq API key is invalid. Check Settings.");
      if (res.status === 429) throw new Error("Groq rate limit hit. Wait a moment and try again.");
      if (res.status === 404) throw new Error(`Groq model "${aiProvider.active_model}" not found. Check Settings.`);
      throw new Error(`Groq API error (${res.status}): ${msg}`);
    }
    const data = await res.json();
    aiResponse = data.choices[0].message.content;

  } else if (aiProvider.provider === "gemini") {
    const res = await fetch(
      `https://generativelanguage.googleapis.com/v1beta/models/${aiProvider.active_model || "gemini-1.5-flash"}:generateContent?key=${aiProvider.api_key}`,
      {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          contents: [{ parts: [{ text: SYSTEM_MESSAGE + "\n\n" + userPrompt }] }],
          generationConfig: { temperature: 0.4, maxOutputTokens: 400 },
        }),
      }
    );
    if (!res.ok) throw new Error(`Gemini API error: ${res.statusText}`);
    const data = await res.json();
    aiResponse = data.candidates[0].content.parts[0].text;

  } else if (aiProvider.provider === "mistral") {
    const res = await fetch("https://api.mistral.ai/v1/chat/completions", {
      method: "POST",
      headers: { "Content-Type": "application/json", Authorization: `Bearer ${aiProvider.api_key}` },
      body: JSON.stringify({
        model: aiProvider.active_model || "mistral-small",
        messages: [{ role: "system", content: SYSTEM_MESSAGE }, { role: "user", content: userPrompt }],
        temperature: 0.4,
        max_tokens: 400,
      }),
    });
    if (!res.ok) throw new Error(`Mistral API error: ${res.statusText}`);
    const data = await res.json();
    aiResponse = data.choices[0].message.content;

  } else {
    throw new Error(`Unsupported AI provider: ${aiProvider.provider}`);
  }

  // ── Parse SUBJECT / BODY from response ────────────────────────────────────
  let subject = "";
  let body = "";

  const subjectMatch = aiResponse.match(/SUBJECT:\s*(.+?)(?:\n|$)/i);
  const bodyMatch = aiResponse.match(/BODY:\s*([\s\S]+?)$/i);

  if (subjectMatch && bodyMatch) {
    subject = subjectMatch[1].trim();
    body = bodyMatch[1].trim();
  } else {
    // Fallback: first line = subject, rest = body
    const lines = aiResponse.trim().split("\n");
    if (lines.length >= 2) {
      subject = lines[0].replace(/^(SUBJECT:|Subject:)/i, "").trim();
      body = lines.slice(1).join("\n").replace(/^(BODY:|Body:)/i, "").trim();
    } else {
      throw new Error("AI response format invalid. Expected 'SUBJECT: ...' and 'BODY: ...' format.");
    }
  }

  subject = stripMarkdown(subject.replace(/^["']|["']$/g, "").trim());
  body = stripMarkdown(body.replace(/^["']|["']$/g, "").trim());

  // Replace any leftover placeholder brackets the AI might output
  body = body
    .replace(/\[Sender Name\]/gi, senderName)
    .replace(/\[Your Name\]/gi, senderName)
    .replace(/\[Name\]/gi, senderName)
    .replace(/\[Title\]/gi, senderTitle)
    .replace(/\[Your Title\]/gi, senderTitle)
    .replace(/\[Company\]/gi, 'Pryro')
    .replace(/\[Your Company\]/gi, 'Pryro');

  if (!subject || !body) {
    throw new Error("AI generated an empty subject or body. Try again.");
  }

  return { subject, body };
}
